# Generated by Django 4.0.2 on 2022-02-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, default='', max_length=500)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('msg', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginInfo', models.CharField(max_length=100)),
                ('passengerInfo', models.CharField(max_length=300)),
                ('passengerCount', models.IntegerField(default=0, editable=False)),
                ('sort_date', models.TextField(blank=True, default='')),
                ('linkComment', models.CharField(blank=True, default='', max_length=200)),
                ('schedule_book', models.BooleanField(default=False)),
                ('cookie', models.CharField(blank=True, default=None, editable=False, max_length=500, null=True)),
                ('bookNumber', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('bookDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('processing', 'Processing'), ('booked', 'Booked'), ('paid', 'Paid')], default='processing', max_length=10)),
                ('runningNode', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.SmallIntegerField(default=1)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.FloatField(blank=True, default=0)),
                ('added_by', models.CharField(blank=True, default='', max_length=20)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkzh.line')),
            ],
        ),
    ]
