# Generated by Django 4.0.2 on 2022-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('linecode', models.CharField(max_length=20)),
                ('maxPeople', models.IntegerField(default=0)),
                ('totalPeople', models.IntegerField(default=0)),
                ('availablePeople', models.IntegerField(default=0)),
                ('saleStatus', models.IntegerField(default=0)),
            ],
        ),
    ]
