# Generated by Django 4.0.2 on 2022-02-15 15:02

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticket_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='user',
            name='schedule_book',
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
