# Generated by Django 3.2.8 on 2022-02-17 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0003_user_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='msg',
            field=models.CharField(blank=True, default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookNumber',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cookie',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginInfo',
            field=models.CharField(help_text='"email,pwd"; Start with # to skip verify', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='passengerInfo',
            field=models.CharField(help_text='"adult1_id,adult1_name,#kid1_id,kid1_name,..."; Kids/Seniors ID start with #', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='sort_date',
            field=models.TextField(blank=True, default='', help_text='Each line for one date; Use -- for date range.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('processing', 'Processing'), ('login', 'Logged in'), ('booked', 'Booked'), ('payment', 'Pending Payment'), ('checking', 'Checking'), ('paid', 'Paid'), ('done', 'Done')], default='processing', max_length=20),
        ),
    ]
