# Generated by Django 4.0.2 on 2022-02-19 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0005_user_paidat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('bank_confirm', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkzh.paycard')),
            ],
        ),
    ]
