# Generated by Django 4.0.2 on 2022-02-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0006_paycard_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0, help_text="Leave 0 to use User's ticket price"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payAt',
            field=models.DateTimeField(blank=True, default=None, help_text='Leave blank to use now', null=True),
        ),
    ]
