# Generated by Django 4.0.3 on 2022-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0009_user_paymentexpireat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, default='', max_length=9000),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginInfo',
            field=models.CharField(help_text='"email,pwd"; Start with # to skip verify with wrong credentials; Start with ! to force input;', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sort_date',
            field=models.TextField(blank=True, default='', help_text='Each line for one date; Use -- for date range; Use * for all schedule date;'),
        ),
    ]
