# Generated by Django 4.0.3 on 2022-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkzh', '0010_user_use_slot_alter_config_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycard',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
