version: '3.1'
networks:
  hkzh:
    driver: bridge
services:
  django:
    env_file:
      - .env
    image: YOUR_IMG_ADDRESS
    networks:
      - hkzh
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ""
      DB_PORT: ""
      DB_PASSWORD: ""
      DB_USER: ""
      TIMEOUT: "10"
      RETRY: "10"
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8082"]
